### Import packages

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

### Load dataset from csv file

In [2]:
original_df = pd.read_csv("Iris.csv")
original_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

Display the data types of each column.

In [3]:
original_df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

### Preprocessing of dataset

First, we drop the unecessary column "Id".

In [4]:
original_df = original_df.drop(columns=["Id"])
original_df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

Next, we remove all the rows with missing data.

In [5]:
original_df = original_df.dropna()
original_df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

We split the "df" dataframe into the feature dataframe "df_X" and the label dataframe "df_Y".

In [6]:
X_df = original_df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
X_df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [7]:
Y_df = original_df[["Species"]]
Y_df

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [8]:
X_train_df, X_test_df, Y_train_df, Y_test_df = train_test_split(X_df, Y_df, test_size=0.2, random_state=37)

In [9]:
X_train = X_train_df.to_numpy()
Y_train = Y_train_df.to_numpy()
X_test = X_test_df.to_numpy()
Y_test = Y_test_df.to_numpy()

In [10]:
scalerX = StandardScaler()
X = scalerX.fit_transform(X_train).T
X.shape

(4, 120)

Create encoder to map categories to float label vectors and store them into the output vector Y.

In [11]:
encoderY = OneHotEncoder(sparse_output=False)
Y = encoderY.fit_transform(Y_train).T
Y.shape
#print("First element of Y:", Y[0])
#print("Last element of Y:", Y[len(Y) - 1])
#Y_first_label = df_Y.to_numpy()[0].reshape(1,1)
#Y_last_label = df_Y.to_numpy()[len(Y) - 1].reshape(1,1)
#assert Y_encoder.inverse_transform(Y_encoder.transform(Y_first_label)) ==  Y_first_label

(3, 120)

## Deep Neural Network

### Initialization

In [12]:
# Shape of the network
xn = X.shape[0]
yn = Y.shape[0]

# Number of units per layer
n = [xn, 4, 4, yn]
# Activations per layer
activations = ["relu", "relu", "softmax"]

In [13]:
# Number of train examples
m = X.shape[1]
m

120

In [14]:
def initialize_parameters(n):
    l = len(n) - 1
    params = {}
    np.random.seed(1)
    for i in range(l):
        params["W"+str(i+1)] = np.random.randn(n[i+1], n[i]) * 0.01
        params["b"+str(i+1)] = np.zeros((n[i+1], 1))

    return params

In [15]:
initialize_parameters(n)

{'W1': array([[ 0.01624345, -0.00611756, -0.00528172, -0.01072969],
        [ 0.00865408, -0.02301539,  0.01744812, -0.00761207],
        [ 0.00319039, -0.0024937 ,  0.01462108, -0.02060141],
        [-0.00322417, -0.00384054,  0.01133769, -0.01099891]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W2': array([[-0.00172428, -0.00877858,  0.00042214,  0.00582815],
        [-0.01100619,  0.01144724,  0.00901591,  0.00502494],
        [ 0.00900856, -0.00683728, -0.0012289 , -0.00935769],
        [-0.00267888,  0.00530355, -0.00691661, -0.00396754]]),
 'b2': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W3': array([[-0.00687173, -0.00845206, -0.00671246, -0.00012665],
        [-0.0111731 ,  0.00234416,  0.01659802,  0.00742044],
        [-0.00191836, -0.00887629, -0.00747158,  0.01692455]]),
 'b3': array([[0.],
        [0.],
        [0.]])}

### Forward pass

In [16]:
def forward_pass_relu(Z):
    return np.maximum(Z, 0.)

In [17]:
relu_Z = np.array([[1,-2,3], 
                   [4,5,-6]])
forward_pass_relu(relu_Z)

array([[1., 0., 3.],
       [4., 5., 0.]])

In [18]:
def forward_pass_softmax(Z):
    Z_exp = np.exp(Z)
    return Z_exp / np.sum(Z_exp, axis=0, keepdims=True)

In [19]:
softmax_Z = np.array([[1,1,1], 
                      [2,1,1]])
forward_pass_softmax(softmax_Z)
#np.sum(softmax_Z, axis=0, keepdims=True)

array([[0.26894142, 0.5       , 0.5       ],
       [0.73105858, 0.5       , 0.5       ]])

In [20]:
def forward_pass_activation(activation, Z):
    match activation:
        case "relu":
            return forward_pass_relu(Z)
        case "softmax":
            return forward_pass_softmax(Z)
        case _:
            raise Exception("No such activation as: "+activation)

In [21]:
def forward_pass(X, n, activations, params):
    l = len(n) - 1
    A = X
    cache = {}
    cache["A"+str(0)] = A
    for i in range(l):
        W = params["W"+str(i+1)]
        b = params["b"+str(i+1)]
        Z = np.dot(W, A) + b
        A = forward_pass_activation(activations[i], Z)
        cache["Z"+str(i+1)] = Z
        cache["A"+str(i+1)] = A
        cache["W"+str(i+1)] = W

    return A, cache

In [22]:
params = initialize_parameters(n)
A, cache = forward_pass(X, n, activations, params)
A.shape

(3, 120)

### Calculating cost

In [23]:
def cost(A, Y, m):
    J = - 1/m * np.sum(np.multiply(Y, np.log(A)))
    return J

In [24]:
cost(A, Y, m)

np.float64(1.0986118157509022)

### Backward pass

In [25]:
def backward_pass_output_layer_softmax(Y, l, m, cache, grads):
    #gradient from non-linear part
    A = cache["A"+str(l)]
    
    dZ = A - Y

    
    #gradient from linear part
    W = cache["W"+str(l)]
    A_prev = cache["A"+str(l-1)]
    
    grads["dW"+str(l)] = 1/m * np.dot(dZ, A_prev.T)
    grads["db"+str(l)] = 1/m * np.sum(dZ, axis= 1, keepdims=True)

    #retruns dA for the previous layer
    return np.dot(W.T, dZ)

In [26]:
def backward_pass_output_layer(Y, n_output, l, activation, m, cache, grads):
    match activation:
        case "softmax":
            return backward_pass_output_layer_softmax(Y, l, m, cache, grads)
        case _:
            raise Exception("No such activation as: "+activation)

In [27]:
def backward_pass_relu(Z):
    return np.where(Z > 0, 1, 0)

In [28]:
def backward_pass_activation(activation, Z):
    match activation:
        case "relu":
            return backward_pass_relu(Z)
        case _:
            raise Exception("No such activation as: "+activation)

In [29]:
def backward_pass_hidden_layers(dA_last, n, activations, m, params, grads):
    l = len(n) - 1
    dA = dA_last
    for i in reversed(range(l)):
        #gradient from non-linear part
        Z = cache["Z"+str(i+1)]
        
        dZ = dA * backward_pass_activation(activations[i], Z)

        
        #gradient from linear part
        W = cache["W"+str(i+1)]           
        A_prev = cache["A"+str(i)]
        
        grads["dW"+str(i+1)] = 1/m * np.dot(dZ, A_prev.T)
        grads["db"+str(i+1)] = 1/m * np.sum(dZ, axis = 1, keepdims=True)

        #dA for the previous layer
        dA = np.dot(W.T, dZ)

    return grads

In [30]:
def backward_pass(Y, n, activations, m, cache):
    l = len(n) - 1
    grads = {}
    dA = backward_pass_output_layer(Y, n[-1], l, activations[-1], m, cache, grads)
    grads = backward_pass_hidden_layers(dA, n[:-1], activations[:-1], m, params, grads)
    return grads

In [31]:
backward_pass(Y,n, activations, m, cache)

{'dW3': array([[-1.87523677e-06,  4.74309855e-05, -1.44472117e-06,
          1.58385423e-05],
        [ 9.37618518e-07, -2.47033551e-05,  8.70523097e-07,
         -3.55034287e-06],
        [ 9.37618251e-07, -2.27276304e-05,  5.74198074e-07,
         -1.22881995e-05]]),
 'db3': array([[-0.00833366],
        [-0.01666626],
        [ 0.02499992]]),
 'dW2': array([[ 3.15789667e-08,  0.00000000e+00,  1.28607721e-07,
          1.04918703e-07],
        [-6.32285390e-06, -2.29897490e-05, -3.48443433e-06,
         -6.38155955e-06],
        [ 1.37903638e-07, -2.85722237e-06,  5.68473962e-07,
          2.38212303e-08],
        [-8.91514425e-06, -5.84174422e-05, -5.46106105e-06,
         -2.98479422e-06]]),
 'db2': array([[ 3.80329764e-05],
        [-6.87396977e-04],
        [ 4.38499246e-04],
        [-2.15389505e-03]]),
 'dW1': array([[ 3.73541896e-06, -4.06331480e-06,  7.30222656e-07,
         -1.21011458e-06],
        [-3.73038641e-06,  1.79094277e-05, -8.61565746e-06,
         -5.43201630e-06],
        [ 1.50159099e-06,  1.06474911e-05, -1.00505838e-06,
         -2.04687159e-06],
        [ 3.00446944e-06,  3.96451458e-06,  1.71386365e-06,
          1.30509027e-06]]),
 'db1': array([[ 1.51766464e-05],
        [-2.52196838e-05],
        [-3.78752686e-06],
        [-1.29438795e-06]])}